name: whatsapp_camera
description: This is a package to open a camera along with a photo gallery, to simplify the steps of the end user
version: 2.0.0

homepage: https://github.com/welitonsousa/whatsapp_camera
repository: https://github.com/welitonsousa/whatsapp_camera
issue_tracker: https://github.com/welitonsousa/whatsapp_camera/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '3.19.4'

dependencies:
  flutter:
    sdk: flutter
  camera_camera: ^3.0.0
  file_picker: ^8.0.0+1
  flutter_sliding_up_panel: ^2.1.1
  photo_gallery: ^2.2.1
  photo_view: ^0.14.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg

